"""initial migration

Revision ID: 4d73e3bedc17
Revises: 886e096f6f21
Create Date: 2016-03-11 00:10:04.259353

"""

# revision identifiers, used by Alembic.
revision = '4d73e3bedc17'
down_revision = '886e096f6f21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
