"""initial migration

Revision ID: 6067d44a2ab0
Revises: 297f7399d6da
Create Date: 2016-03-10 15:18:18.958672

"""

# revision identifiers, used by Alembic.
revision = '6067d44a2ab0'
down_revision = '297f7399d6da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
