"""initial migration

Revision ID: ad1054a095b4
Revises: b3771b2cc4ea
Create Date: 2016-03-09 19:45:03.419299

"""

# revision identifiers, used by Alembic.
revision = 'ad1054a095b4'
down_revision = 'b3771b2cc4ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
